### PR TITLE
Vanilla v1

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Updated the codebase to support Vanilla v1+. Add the new global navigation module.

## QA
- Pull a branch
- Run `./run`
- Open up http://0.0.0.0:8012/
- Check the page looks good on all view ports
- Check the size of the page has shrunk from the live site
- Check that there are no accessibility errors when testing with AA
- Check that the markup is valid

## Issue / Card
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/9 https://github.com/ubuntudesign/vanilla-squad/issues/10 https://github.com/canonical-websites/jp.ubuntu.com/issues/20 https://github.com/canonical-websites/jp.ubuntu.com/issues/18 https://github.com/canonical-websites/jp.ubuntu.com/issues/16 https://github.com/canonical-websites/jp.ubuntu.com/issues/15

## Screenshots
ubuntu 1

## Demo
http://jp.ubuntu.com-vanilla-v1.demo.haus

### CODE REVIEW

**Comment by yaili** [comment]
Design notes:
- [ ] For the icons in the hero, can you use the same as in ubuntu.com without the words and links?
- [ ] Is link colour related to brand colour? How could we make them orange like u.com?
- [ ] Image in "Ubuntu はクラウドに最適" doesn't look vector, like on live - can you update?
- [ ] Can we use the pull quote pattern in "Ubuntu OpenStack で、プライベート クラウドを構築" with the Japanese quotation marks?
- [ ] Can we use a larger image in "サービスまたはサポートが必要ですか?" like on live?
- [ ] Logos are really big in "パブリック クラウドでの Ubuntu の利用"…
- [ ] Why does the button in contextual footer not align left with rest of text?

Thanks

**Comment by WillMoggridge** [comment]
Code and QA is looking good, pending design tweaks

**Comment by anthonydillon** [comment]
@yaili all design review points have been addressed. Apart from the PNG which we need as a vector in the Ubuntu はクラウドに最適 section.

**Comment by anthonydillon** [comment]
@yaili @WillMoggridge all design points addressed.

**Comment by yaili** [comment]
Following our chat, I think the quotation marks need to look as on live, other than that looks good.

**Pull request merged**
